// <auto-generated />
using System;
using GestionParcMateriel.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionParcMateriel.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812094048_AddUtilisateur")]
    partial class AddUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionParcMateriel.API.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Poste")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Service")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Matricule")
                        .IsUnique()
                        .HasDatabaseName("IX_Employe_Matricule");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.EtatMateriel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique()
                        .HasDatabaseName("IX_EtatMateriel_Libelle");

                    b.ToTable("EtatsMateriels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Libelle = "En stock"
                        },
                        new
                        {
                            Id = 2,
                            Libelle = "Affecté"
                        },
                        new
                        {
                            Id = 3,
                            Libelle = "En maintenance"
                        },
                        new
                        {
                            Id = 4,
                            Libelle = "Panne"
                        },
                        new
                        {
                            Id = 5,
                            Libelle = "HS"
                        },
                        new
                        {
                            Id = 6,
                            Libelle = "Rebut"
                        });
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.Localisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("IX_Localisation_Nom");

                    b.ToTable("Localisations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Salle Serveur"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Administration"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Atelier"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Magasin"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Direction"
                        });
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.Materiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CodeBarre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Commentaires")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAcquisition")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateModification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("EtatId")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LocalisationId")
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modele")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TypeMaterielId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodeBarre")
                        .IsUnique()
                        .HasDatabaseName("IX_Materiel_CodeBarre");

                    b.HasIndex("EmployeId");

                    b.HasIndex("EtatId");

                    b.HasIndex("LocalisationId");

                    b.HasIndex("NumeroSerie")
                        .IsUnique()
                        .HasDatabaseName("IX_Materiel_NumeroSerie")
                        .HasFilter("[NumeroSerie] IS NOT NULL");

                    b.HasIndex("TypeMaterielId");

                    b.ToTable("Materiels");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.MouvementMateriel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AncienEtatId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaires")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateMouvement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("LocalisationId")
                        .HasColumnType("int");

                    b.Property<int>("MaterielId")
                        .HasColumnType("int");

                    b.Property<int>("NouvelEtatId")
                        .HasColumnType("int");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AncienEtatId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("LocalisationId");

                    b.HasIndex("MaterielId");

                    b.HasIndex("NouvelEtatId");

                    b.ToTable("MouvementsMateriels");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.TypeMateriel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique()
                        .HasDatabaseName("IX_TypeMateriel_Libelle");

                    b.ToTable("TypesMateriels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Libelle = "PC Portable"
                        },
                        new
                        {
                            Id = 2,
                            Libelle = "PC Fixe"
                        },
                        new
                        {
                            Id = 3,
                            Libelle = "Écran"
                        },
                        new
                        {
                            Id = 4,
                            Libelle = "Imprimante"
                        },
                        new
                        {
                            Id = 5,
                            Libelle = "Scanner"
                        },
                        new
                        {
                            Id = 6,
                            Libelle = "Switch"
                        },
                        new
                        {
                            Id = 7,
                            Libelle = "Routeur"
                        },
                        new
                        {
                            Id = 8,
                            Libelle = "Téléphone IP"
                        });
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Utilisateur_Email");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@sopal.tn",
                            MotDePasseHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            NomComplet = "Administrateur SOPAL",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.Materiel", b =>
                {
                    b.HasOne("GestionParcMateriel.API.Models.Employe", "Employe")
                        .WithMany("Materiels")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionParcMateriel.API.Models.EtatMateriel", "Etat")
                        .WithMany("Materiels")
                        .HasForeignKey("EtatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionParcMateriel.API.Models.Localisation", "Localisation")
                        .WithMany("Materiels")
                        .HasForeignKey("LocalisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionParcMateriel.API.Models.TypeMateriel", "TypeMateriel")
                        .WithMany("Materiels")
                        .HasForeignKey("TypeMaterielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Etat");

                    b.Navigation("Localisation");

                    b.Navigation("TypeMateriel");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.MouvementMateriel", b =>
                {
                    b.HasOne("GestionParcMateriel.API.Models.EtatMateriel", "AncienEtat")
                        .WithMany("MouvementsAncienEtat")
                        .HasForeignKey("AncienEtatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionParcMateriel.API.Models.Employe", "Employe")
                        .WithMany("Mouvements")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionParcMateriel.API.Models.Localisation", "Localisation")
                        .WithMany("Mouvements")
                        .HasForeignKey("LocalisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionParcMateriel.API.Models.Materiel", "Materiel")
                        .WithMany("Mouvements")
                        .HasForeignKey("MaterielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionParcMateriel.API.Models.EtatMateriel", "NouvelEtat")
                        .WithMany("MouvementsNouvelEtat")
                        .HasForeignKey("NouvelEtatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AncienEtat");

                    b.Navigation("Employe");

                    b.Navigation("Localisation");

                    b.Navigation("Materiel");

                    b.Navigation("NouvelEtat");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.Employe", b =>
                {
                    b.Navigation("Materiels");

                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.EtatMateriel", b =>
                {
                    b.Navigation("Materiels");

                    b.Navigation("MouvementsAncienEtat");

                    b.Navigation("MouvementsNouvelEtat");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.Localisation", b =>
                {
                    b.Navigation("Materiels");

                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.Materiel", b =>
                {
                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("GestionParcMateriel.API.Models.TypeMateriel", b =>
                {
                    b.Navigation("Materiels");
                });
#pragma warning restore 612, 618
        }
    }
}
